sudo: required
services:
  - docker

before_install:
  - docker build -t johnantonusmaximus/react-app-ci-cd -f Dockerfile.dev . 

script:
  - docker run johnantonusmaximus/react-app-ci-cd npm run test -- --coverage